---
- name: "Add google-chrome source repo"
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  become: true

- name: "Add google-chrome gpg key"
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    # file: /etc/apt/trusted.gpg.d/google.gpg

- name: "Install google-chrome"
  apt:
    name:
      - google-chrome-stable
    update_cache: yes
  become: true
