---
# tasks file for notejam-django-installation

# - name: Wait for any possibly running unattended upgrade to finish
#   raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

# - name: Manually update packages list (problem with update_cache)
#   command: echo hello
#   become: yes

- name: Update apt-get repo and cache
  apt:
    update_cache=yes
    force_apt_get=yes
    cache_valid_time=0
  become: true

- name: "Install deps"
  apt:
    name:
      - xorg
      - pulseaudio
      - pulsemixer
      - cmake
      - htop
      - xinit
      - flatpak
      - qbittorrent
      - git
      - mpv
      - sxiv
      - pcmanfm
      - ffmpegthumbnailer
      - chromium
      - curl
      - x11-xserver-utils
      - fonts-noto-mono
      - fonts-symbola
      - linux-headers-generic
      - build-essential
      - dkms
      - xclip
      - neovim
      - open-vm-tools-desktop
      - libxrender-dev
      - automake
      - xutils-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libtool-bin
      - libtool
      - x11proto-dev
      - libx11-dev
      - libxinerama-dev
    update_cache: yes
    state: present
  become: true

# - name: "Add google-chrome source repo"
#     ansible.builtin.apt_repository:
#       repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
#   become: true

# - name: "Add google-chrome gpg key"
#   ansible.builtin.apt_key:
#     url: https://dl.google.com/linux/linux_signing_key.pub
#     # file: /etc/apt/trusted.gpg.d/google.gpg

# - name: "Install google-chrome"
#   apt:
#     name:
#       - google-chrome-stable
#     update_cache: yes
#   become: true

# - name: "Install docker deps"
#   apt:
#     name:
#       - ca-certificate
#       - curl
#       - gnugpg
#       - lsb-release
#     update_cache: yes
#   become: true

# - name: "Add docker gpg key"
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/debian/gpg
#     # file: /usr/share/keyrings/docker-archive-keyring.gpg

# - name: "Add docker source repo"
#   ansible.builtin.apt_repository:
#     repo: deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable
#   become: true

# - name: "Install docker"
#   apt:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#     update_cache: yes
#   become: true

# - name: "Clone repo"
#   git:
#     repo: https://github.com/komarserjio/notejam.git
#     dest: notejam
#     accept_hostkey: yes
#     force: yes
